# Generated by Django 5.1.7 on 2025-03-27 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('unidade', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=10)),
                ('codigo', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=11)),
                ('obra', models.CharField(blank=True, max_length=200)),
                ('descricao', models.TextField()),
                ('io', models.CharField(blank=True, max_length=10)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insumo', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('unidade', models.CharField(max_length=20)),
                ('data_custo', models.DateField(blank=True, null=True)),
                ('valor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ComposicaoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('composicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copre_depre.composicao')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copre_depre.insumo')),
            ],
        ),
    ]
