# Generated by Django 5.1.7 on 2025-03-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copre_depre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='composicaoinsumo',
            name='codigo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='composicaoinsumo',
            name='data_custo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='composicaoinsumo',
            name='un',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='composicaoinsumo',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='composicao',
            name='io',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='composicao',
            name='obra',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='insumo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidade',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
