# Generated by Django 5.1.7 on 2025-04-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copre_depre', '0002_composicaoinsumo_codigo_composicaoinsumo_data_custo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composicao',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='composicao',
            name='io',
            field=models.DateField(),
        ),
    ]
